name: Sync Legal Events Calendar

on:
  schedule:
    # Run daily at 6 AM UTC (1 AM EST, 2 AM EDT)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scrapers/**'
      - 'populate_database.py'
      - 'calendar_api.py'

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r scrapers/requirements.txt
        
    - name: Run scrapers and populate database
      run: |
        python populate_database.py
        
    - name: Test calendar API
      run: |
        python -c "
        from calendar_api import CalendarAPI
        api = CalendarAPI()
        events = api.get_events()
        print(f'Found {len(events)} events')
        
        # Test ICS generation
        ics = api.generate_ics(events)
        print(f'Generated ICS: {len(ics)} characters')
        
        # Test JSON generation
        json_data = api.generate_json(events)
        print(f'Generated JSON: {len(json_data[\"data\"])} events')
        "
        
    - name: Upload calendar files
      uses: actions/upload-artifact@v3
      with:
        name: calendar-files
        path: |
          legal_events.ics
          events.db
          
    - name: Deploy to Vercel (if API_TOKEN is available)
      if: env.API_TOKEN != ''
      run: |
        # Trigger Vercel deployment
        curl -X POST https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_DEPLOY_HOOK }} \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
          
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Calendar sync completed successfully"
        echo "📅 Events updated and calendar generated"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Calendar sync failed"
        echo "Please check the logs for errors"


