name: Run Scrapers

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        cd scrapers
        pip install -r requirements.txt
        
    - name: Run scrapers
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SCRAPER_SECRET: ${{ secrets.SCRAPER_SECRET }}
        VERCEL_URL: ${{ secrets.VERCEL_URL }}
      run: |
        cd scrapers
        python cron_handler_db.py 